update: update parameters of a lidar and an imu
2024-Integration-Training-Sparow/sample_sensor_kit_launch-sparrow pull request #1
Opened 2024-04-12 07:45 UTC by shtokuda

I updated parameters of sensors of Sparrow

2024-04-17 09:12 UTC, zusizusi requested changes

2024-04-17 09:12 UTC, zusizusi commented on sample_sensor_kit_description/config/sensors_calibration.yaml
> +    z: 0.1000
base_linkより10cm高いことになってしまってます。

2024-04-17 09:12 UTC, zusizusi commented on sample_sensor_kit_description/urdf/sensor_kit.xacro
> +    <xacro:include filename="$(find velodyne_description)/urdf/VLP-32.urdf.xacro"/>
velodyne_descriptionに存在しないと言われるのを防ぐため、velodyne_descriptionに追加するか、他のパッケージに追加してパッケージ名を書き換える必要がありそうです。

2024-04-17 09:56 UTC, zusizusi requested changes

2024-04-17 09:56 UTC, zusizusi commented on sample_sensor_kit_description/config/imu_corrector.param.yaml
> +/**:
個々の機体のパラメータだと思うのでindividual paramのパッケージに入れたほうがいいかもです。

2024-04-17 23:55 UTC, masahiro-kubota commented on sample_sensor_kit_description/urdf/sensor_kit.xacro
> +    <xacro:include filename="$(find velodyne_description)/urdf/VLP-32.urdf.xacro"/>
既に話しているかもしれませんが、sensor_component_descriptionもtokudaをmainにマージすれば大丈夫そうですかね。

2024-04-17 23:58 UTC, masahiro-kubota commented on sample_sensor_kit_description/urdf/sensor_kit.xacro
> +    <xacro:include filename="$(find velodyne_description)/urdf/VLP-32.urdf.xacro"/>
すみません。リポジトリのURLを変える必要がありますね。。。

2024-04-18 03:28 UTC, masahiro-kubota approved these changes
LGTM

2024-04-18 04:39 UTC, merged